name: Frontend Tests
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_baseUrl: 'https://deploy-preview-${{ github.event.number }}--tender-stonebraker-78d2e4.netlify.app'
        with:
          wait-on: 'https://deploy-preview-${{ github.event.number }}--tender-stonebraker-78d2e4.netlify.app'
          wait-on-timeout: 90
          component: false
          config-file: cypress.config.js
